success() テスト

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -10,8 +10,12 @@ jobs:
     steps:
         - name: success
           run: exit 0
-  failure-job:
-    runs-on: ubuntu-latest
-    steps:
-        - name: failure
-          run: exit 1
+        - name: if success execute
+          if: success()
+          run: echo 'in success'
+
+#   failure-job:
+#     runs-on: ubuntu-latest
+#     steps:
+#         - name: failure
+#           run: exit 1
