failure テスト

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -5,22 +5,24 @@ on:
   pull_request:
 
 jobs:
-#   success-job:
-#     runs-on: ubuntu-latest
-#     steps:
-#         - name: success
-#           run: exit 0
-#         - name: if success execute
-#           if: success()
-#           run: echo 'in success'
+    # failure：true
+    failure-job:
+        runs-on: ubuntu-latest
+        steps:
+            - name: failure
+              run: exit 1
+            - name: if failure execute
+              # 前のjobが失敗(exit 1)しているので、以下jobも実行される
+              if: failure()
+              run: echo 'in failure'
 
-  failure-job:
-    runs-on: ubuntu-latest
-    steps:
-        - name: failure
-          run: exit 1
-        - name: success
-          run: exit 0
-        - name: if failure execute
-          if: failure()
-          run: echo 'in failure'
+    # failure：false
+    success-job:
+        runs-on: ubuntu-latest
+        steps:
+            - name: success
+              run: exit 0
+            - name: if failure execute
+              # 前のjobが成功(exit 0)しているので、以下jobは実行されない
+              if: failure()
+              run: echo 'in failure'
