failure テスト

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -5,17 +5,20 @@ on:
   pull_request:
 
 jobs:
-  success-job:
-    runs-on: ubuntu-latest
-    steps:
-        - name: success
-          run: exit 0
-        - name: if success execute
-          if: success()
-          run: echo 'in success'
-
-#   failure-job:
+#   success-job:
 #     runs-on: ubuntu-latest
 #     steps:
-#         - name: failure
-#           run: exit 1
+#         - name: success
+#           run: exit 0
+#         - name: if success execute
+#           if: success()
+#           run: echo 'in success'
+
+  failure-job:
+    runs-on: ubuntu-latest
+    steps:
+        - name: failure
+          run: exit 1
+        - name: if failure execute
+          if: failure()
+          run: echo 'in failure'
